apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: demo
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: demo-chart
      version: ">0.1.0.0"
      sourceRef:
        kind: HelmRepository
        name: demo-repo
        namespace: flux-system
  values:
    replicaCount: 1
